baseURL = "https://flourishing-stardust-b38d10.netlify.app/"
languageCode = "ja"
title = "my-blog"
theme = "hugo-theme-stack"

# æ—¥æœ¬èªè¨˜äº‹ã§ã‚‚å¤‰ãªURLã«ãªã‚‰ãªã„ã‚ˆã†ã«
hasCJKLanguage = true

[pagination]
pagerSize = 10

# ãƒ“ãƒ«ãƒ‰é–¢é€£
enableEmoji = true
enableGitInfo = true

[params]
  description = "ãƒ—ãƒ­ã‚°ãƒ©ãƒãƒ¼ã®é›‘è¨˜ãƒ–ãƒ­ã‚°ã€‚æŠ€è¡“ãƒ»ã‚²ãƒ¼ãƒ ãƒ»æ—¥å¸¸ã€‚"
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true

  # ã‚µã‚¤ãƒ‰ãƒãƒ¼è¡¨ç¤º
  
    [params.sidebar]
    enabled = true
    emoji = "ğŸ¦™"
    subtitle = "ã‚³ãƒ¼ãƒ‰ã¨ã‚²ãƒ¼ãƒ ã¨æ—¥å¸¸"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

    [params.profile]
    enabled = true
    name = "alpaca0601"
    bio = """
    éƒ½å†…ã§åƒããƒ—ãƒ­ã‚°ãƒ©ãƒãƒ¼ã€‚
    ã‚²ãƒ¼ãƒ ã¨ã‚³ãƒ¼ãƒ‰ã¨é©å½“ãªé›‘è¨˜ã‚’æ›¸ã„ã¦ã„ãã¾ã™ã€‚

    Hugo + Stack + Netlify æ§‹æˆã§è©¦é¨“çš„ã«ãƒ–ãƒ­ã‚°é‹å–¶ä¸­ã€‚
    """

  # ãƒ•ãƒƒã‚¿ãƒ¼
  [params.footer]
    since = 2025
    customText = "Powered by Hugo & Stack"

  # è¨˜äº‹è¨­å®š
  [params.article]
    math = false
    toc = true
    readingTime = true

  # æ—¥ä»˜è¡¨è¨˜
  [params.dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02 15:04"

  # SNS
  [[params.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/alpaca0601"

  [[params.social]]
    identifier = "twitter"
    name = "Xï¼ˆåœæ­¢ä¸­ï¼‰"
    url = "https://x.com/alpaca_stream"

# æ—¥æœ¬èªãƒ¡ãƒ‹ãƒ¥ãƒ¼
[menu]
  [[menu.main]]
    identifier = "home"
    name = "ãƒ›ãƒ¼ãƒ "
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "è¨˜äº‹"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«"
    url = "/about/"
    weight = 3
